package endpoints

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

type endpointStruct struct {
	Version   int
	Endpoints map[string]endpointEntry
}

type endpointEntry struct {
	Endpoint      string
	SigningRegion string
}

var endpointsMap = endpointStruct{
	Version: 2,
	Endpoints: map[string]endpointEntry{
		"*/ec2": {
			Endpoint: "{region}.cp.cloud.nifty.com/api",
		},
		"east-1/s3": {
			Endpoint: "ncss.nifty.com",
		},
		"west-1/s3": {
			Endpoint: "west-1-ncss.nifty.com",
		},
		"*/rdb": {
			Endpoint: "rdb.jp-{region}.api.cloud.nifty.com",
		},
		"*/dns": {
			Endpoint: "dns.api.cloud.nifty.com",
		},
		"*/ess": {
			Endpoint: "ess.api.cloud.nifty.com",
		},
	},
}
